# 베이스 이미지 지정
FROM ubuntu:latest

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y apache2 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install tensorflow numpy flask flask-cors Pillow

# 작업 디렉터리를 지정
WORKDIR /var/www/html/

# COPY는 호스트의 파일이나 디렉터리를 컨테이너의 파일이나 디렉터리로 복사합니다.
# 예를 들어, 현재 디렉터리의 모든 파일을 컨테이너의 /app 디렉터리로 복사합니다.
COPY . /var/www/html/

# 웹 서버 포트 열기
EXPOSE 80
EXPOSE 5000

# 웹 서버 실행
CMD ["bash", "-c", "apachectl -D FOREGROUND & python3 /var/www/html/python.py"]
# CMD ["apachectl", "-D", "FOREGROUND"]