# 베이스 이미지 지정
FROM ubuntu:latest

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y apache2 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# 작업 디렉터리를 지정
WORKDIR /app

# COPY는 호스트의 파일이나 디렉터리를 컨테이너의 파일이나 디렉터리로 복사합니다.
# 예를 들어, 현재 디렉터리의 모든 파일을 컨테이너의 /app 디렉터리로 복사합니다.
COPY . /app

# Tensorflow 설치
RUN pip3 install tensorflow

# numpy 설치
RUN pip3 install numpy

# 웹 서버 포트 열기
EXPOSE 10080

# 웹 페이지 파일 복사
COPY index.html /var/www/html/

# 웹 서버 실행
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]